name: news_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # TODO: State Management
  flutter_bloc: ^8.1.3

  #TODO: icon
  ionicons: ^0.1.2

  # TODO: Comparing dart objects
  equatable: ^2.0.5

  # TODO: Service locator
  get_it: ^7.6.4

  # TODO: Date Format
  intl: ^0.18.1

  # TODO: Local Database
  floor: ^1.4.2

  # TODO: Make request to api
  retrofit: ^4.0.2

  # TODO: Hooks
  flutter_hooks: ^0.20.3

  # TODO: Cahed image
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
  retrofit_generator: ^8.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
